name: Build and Publish WPF Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish WpfAction.csproj -c Release -o publish --self-contained true -r win-x64 /p:PublishSingleFile=true
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WpfAction-Release
        path: publish/
        retention-days: 30  # Los artefactos se guardarán por 30 días
