name: Build and Publish WPF Application
on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'  # Activar el workflow cuando se cree un tag que comience con 'v'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore WpfAction/WpfAction.csproj
    
    # Nuevo paso para reemplazar el placeholder de licencia con el secreto
    - name: Replace License Key
      run: |
        $content = Get-Content -Path .\WpfAction\MainWindow.xaml.cs -Raw
        $content = $content -replace 'LICENSE_KEY_PLACEHOLDER', '${{ secrets.LICENSE_KEY }}'
        # O si mantienes la cadena original, reemplázala directamente:
        # $content = $content -replace '"FFF999-EE4RT-WWWER-33GSW"', '"${{ secrets.LICENSE_KEY }}"'
        Set-Content -Path .\WpfAction\MainWindow.xaml.cs -Value $content
      shell: pwsh
      
    - name: Build
      run: dotnet build WpfAction/WpfAction.csproj --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish WpfAction/WpfAction.csproj -c Release -o publish --self-contained true -r win-x64 /p:PublishSingleFile=true
      
    # Comprimir los archivos publicados
    - name: Zip the published files
      run: |
        cd publish
        Compress-Archive -Path * -DestinationPath ../WpfAction.zip
      shell: pwsh
      
    # Crear una release cuando se empuje un tag
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: WpfAction.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        
    # También subir como artefacto para builds no taggeados
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WpfAction-Release
        path: publish/